<?php

/**
 * Copyright © Elgentos. All rights reserved.
 * https://elgentos.nl
 */

declare(strict_types=1);

// phpcs:disable Generic.Files.LineLength.TooLong

/**
 * @var Template $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
?>
<div class="fixed right-0 bottom-0 p-4">
    <div x-data>
        <button
            @click="$dispatch('show-consent-popup')"
            class="flex justify-center items-center bg-primary shadow-lg rounded-full text-xl md:text-2xl w-12 h-12 md:w-14 md:h-14"
            title="<?= $escaper->escapeHtmlAttr(__('Update Cookie Settings')) ?>"
        >
            <span>🍪</span>
        </button>
    </div>
</div>
